### ISSUE TITLE
length function

### ISSUE THREAD

**Issue by CaptRat** [learn-co-curriculum/javascript-arrays#24]
var iceCreams = ["chocolate", "vanilla", "raspberry"]
 
iceCreams.slice(0, iceCreams.length - 1) // ["chocolate", "vanilla"]
Aren't 
   iceCreams.slice(0) = "chocolate" and 
   iceCreams.slice(iceCreams.length-1) = "raspberry" (not "vanilla!)?
 
iceCreams // ["chocolate", "vanilla", "raspberry"]

**Comment by aturkewi** [comment]
Hey @CaptRat thanks for raising this issue. Did you try this in the chrome console? The code is correct for:

```js
var iceCreams = ["chocolate", "vanilla", "raspberry"]

iceCreams.slice(0, iceCreams.length - 1) // ["chocolate", "vanilla"]
```

If you're having trouble _why_ this is the case, I think that question might be better suited for AskAQuestion rather than raising an issue with the lab. 

The short answer is that when you pass `slice()` a second argument, you are not simply saying 'and get the item store in that index as well', you're rather saying, 'start at index X, and return to me the next Y number of items', where X is the first argument `0`, and Y is the second argument `iceCreams.length - 1 // 2`.

**Comment by aturkewi** [comment]
Hey @CaptRat thanks for raising this issue. Did you try this in the chrome console? The code is correct for:

```js
var iceCreams = ["chocolate", "vanilla", "raspberry"]

iceCreams.slice(0, iceCreams.length - 1) // ["chocolate", "vanilla"]
```

If you're having trouble _why_ this is the case, I think that question might be better suited for AskAQuestion rather than raising an issue with the lab. 

The short answer is that when you pass `slice()` a second argument, you are not simply saying 'and get the item store in that index as well', you're rather saying, 'start at index X, and return to me the next Y number of items', where X is the first argument `0`, and Y is the second argument `iceCreams.length - 1 // 2`.
