### ISSUE TITLE
the 'Submit Pull Request' button dos not active

### ISSUE THREAD

**Issue by misshwr** [learn-co-curriculum/javascript-arrays#67]
I have done many lab tasks and as I passed the mission the 'Submit Pull Request' button dos not active, and  Tech Coaches has not cooperated with this issue.

Thank you for supporting

**Comment by maxwellbenton** [comment]
Hi @misshwr, 

Sorry to hear that you were experiencing problems with Learn. This issue is due to a bug in Learn, and our engineering team has been notified. If you continue to experience this issue on future lessons, please feel free to reach out to support@learn.co for further assistance.

Thank you!
